source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'CCLiveCloud' do
pod 'Masonry'
#pod 'Bugly'
pod 'SDWebImage', '~> 4.0.0'
#pod 'MBProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'AFNetworking'
#pod 'CCLivePlaySDK', '~> 3.7.0'

end
